CREATE TABLE `users`.`user` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `email` VARCHAR(100) NOT NULL DEFAULT '',
  `password` VARCHAR(100) NOT NULL DEFAULT '',
  `active` BOOLEAN NOT NULL DEFAULT 1,
  PRIMARY KEY(`id`)
)
ENGINE = InnoDB;

CREATE TABLE `users`.`roles` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(`id`)
)
ENGINE = InnoDB;

ALTER TABLE `users`.`user` MODIFY COLUMN `id` INTEGER UNSIGNED NOT NULL,
 ADD COLUMN `role_id` INTEGER UNSIGNED NOT NULL DEFAULT 2 AFTER `password`;
 
CREATE TABLE `users`.`access_types` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `access_type` VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY(`id`)
)
ENGINE = InnoDB;

CREATE TABLE `users`.`role_access` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `access_id` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(`id`)
)
ENGINE = InnoDB;

ALTER TABLE `users`.`access_types` ADD COLUMN `description` VARCHAR(255) NOT NULL DEFAULT '' AFTER `access_type`,
 ADD COLUMN `active` BOOLEAN NOT NULL DEFAULT 1 AFTER `description`;