CREATE TABLE `users`.`user` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `email` VARCHAR(100) NOT NULL DEFAULT '',
  `password` VARCHAR(100) NOT NULL DEFAULT '',
  `active` BOOLEAN NOT NULL DEFAULT 1,
  PRIMARY KEY(`id`)
)
ENGINE = InnoDB;